(function () {
    "use strict";
    angular.module('app').config(translate);
    translate.$inject = ['$translateProvider', 'tmhDynamicLocaleProvider'];
    function translate($translateProvider, tmhDynamicLocaleProvider) {
        $translateProvider.translations('en', {
            SEARCH: 'Search',
            SUMMARY: 'Summary Report',
            SUBMIT: 'SUBMIT',
            ADD_USER: 'Add User',
            FIRST_NAME: 'First Name ',
            LAST_NAME: 'Last Name ',
            MOBILE_NUMBER: 'Mobile Number ',
            EMAIL_ADDRESS: 'Email Address ',
            NATIONAL_ID: 'National ID ',
            SELECT_USER_TYPE: 'Select User Type',
            DESCRIPTION_OPTIONAL: 'Description ..(Optional)',
            BUTTON_LANG_EN: 'English',
            BUTTON_LANG_AR: 'العربية',
            BUILDING_LIST_TITLE: 'building',
            ADD_BUILDING: 'Add Building',
            CLEAR_BTN: 'Clear Selection',
            CLEAR: 'Clear',
            DELETE_BTN: 'Delete Selection',
            BUILDING_ID: 'Building ID',
            BUILDING_TYPE: 'Building Type',
            BUILDING_NAME: 'Building Name',
            BUILDING_COUNTRY: 'Country ',
            BUILDING_CITY: 'City ',
            ACTIONS: 'Actions',
            FILTER: 'Filter',
            DASHBOARD: 'Dashboard',
            LOADING_ACTIVITIES: 'loading activities',
            MAPS: 'Maps',
            PICKUPS: 'Pickups',
            DELIVERABLE: 'Deliverable',
            HUB_MANAGEMENT: 'Hub Management',
            PACKAGES: 'packages',
            PACKAGE: 'package',
            TRACKING_PACKAGES: 'tracking packages',
            CUSTOMERS: 'customers',
            REPORTS: 'Reports',
            USER_FEATURES: 'User Features',
            ON_DEMAND_REQUESTS: 'On Demand Requests',
            SCHEDULE_REQUESTS: 'Schedule Requests',
            HISTORY_PICKUP: 'pickup history ',
            USERS: 'users',
            ROLES: 'roles & permissions',
            BUILDINGS: 'Buildings',
            VEHICLES: 'vehicles',
            CITY_VIEW: 'City View',
            VEHICLE_VIEW: 'vehicle view',
            ARCHIVED_REQUESTS: 'Archived Requests',
            OPERATION_CENTER: 'operation center',
            DELIVERY: 'Delivery',
            RETURN: 'Return',
            FILTER_VEHICLE: 'Filter By Vehicle Name',
            OPERATION_CENTER_SEARCHBY: 'Select Operation Center',
            AVALIABLE_VEHICLE: 'Avaliable Vehicles',
            BUSY_VEHICLE: 'Busy Vehicle',
            PROFILE: 'Profile',
            PROFILE_SUCCESS_UPDATE: 'profile updated successfully',
            LOCK_USER: 'Lock User',
            SIGN_OUT: 'Sign Out',
            COPY_RIGHTS: 'Copyrights Reserved 2016 to',
            TODAY: 'Today',
            RESET: 'Reset',
            ON_DEMAND_PICKUP_REQUESTS: 'on demand pickup',
            ID: 'ID',
            PICKUP_CITY: 'Pickup City',
            PICKUP_AREA: 'Pickup Area',
            PACKAGE_TYPE: 'Package Type',
            PICKUP_TYPE: 'Pickup Type',
            PACKAGE_WEIGHT: 'Package Weight',
            RECEIVED_FROM: 'Received From',
            REQUEST_STATUS: 'Request Status',
            SCHEDULED_PICKUP_REQUEST: 'scheduled pickup request',
            REQUEST_ID: 'Request ID',
            REQUEST_TYPE: 'Request Type',
            REQUESTS_TYPES: 'Requests Types',
            REQUEST_MOBILE: 'Requester Mobile Number',
            FROM: 'From',
            TO: 'To',
            REQUEST_DATE: 'Request Date',
            PICKUP_DATE: 'Pickup Date',
            APPLY_FILTRATION: 'Apply Filtration',
            RESET_DATA: 'Reset Data',
            TIME_INTERVAL: 'Time Interval',
            RETURN_TIME_INTERVAL: 'Return Time Interval',
            TOTAL_REQUESTS: 'Total Requests',
            STATUS: 'Status',
            ON_DEMAND_PICKUP_DETAILS: 'on demand pickup details',
            SCHEDULED_PICKUP_DETAILS: 'scheduled pickup details',
            REQUEST_DETAILS: 'request details',
            REQUESTER_ID: 'Requester ID',
            REQUESTER_NAME: 'Requester Name',
            SENDER: 'sender',
            SENDER_NAME: 'Sender Name',
            REQUEST_TIME_UTC: 'Request Time UTC',
            PICKUP_DETAILS: 'pickup details',
            PICKUP_ADDRESS: 'Pickup Address',
            PICKUP_TIME_UTC: 'Pickup Time UTC',
            PACKAGE_DETAILS: 'package details',
            PACKAGE_ID: 'Package ID',
            PACKAGE_NICKNAME: 'Package Nickname',
            PACKAGE_WEIGHT_KG: 'Package Weight (kg)',
            PACKAGE_DIMENSION_CM: 'Package Dimension (cm)',
            PACKAGE_DIMENSION: 'Package Dimension',
            PACKAGE_CONTAINER_LABELING: 'Package Container Labeling',
            PACKAGE_BRIEF: 'Package Brief',
            SHIPPING_RECIPIENT_DETAILS: 'shipping & recipient details',
            SHIPPING_SERVICE: 'Shipping Service',
            SUB_SHIPPING_SERVICE: 'Sub Shipping Service',
            RECIPIENT_FULL_NAME: 'Recipient Full Name',
            RECIPIENT_NAME: 'Recipient Name',
            RECIPIENT_MOBILE_NUMBER: 'Recipient Mobile Number',
            RECIPIENT_ADDRESS: 'Recipient Address',
            RECIPIENT: 'recipient',
            ADDITIONAL_INFORMATION: 'Additional Information',
            PAYMENT_DETAILS: 'payment details',
            PAYMENT_AT: 'Payment At',
            PAYMENT_METHOD: 'Payment Method',
            ADDITIONAL_SERVICES: 'additional services',
            WRAP_LABEL: 'Wrap & Label',
            PACKAGING_BOX: 'Packaging Box',
            PICKUP_SCHEDULED_FOR: 'pickup scheduled for',
            WITH_TIME_INTERVAL: 'with time interval',
            ADD_PACKAGE: 'Add Package',
            GROUP_NAME: 'Group Name',
            UDER_ID: 'User ID',
            FULL_NAME: 'Full Name',
            TOTAL_CUSTOMER: 'Total Customers',
            ADDRESS: 'Address',
            ADD_VEHICLE: 'Add Vehicle',
            VEHICLE_ID: 'Vehicle ID',
            VEHICLE_TYPE: 'Vehicle Type',
            VEHICLE_MOTOR: 'Vehicle Motor',
            VEHICLE_PLATE_NO: 'Vehicl Plate No.',
            BRAND: 'Brand',
            PLATE_NO: 'Plate No.',
            PURPOSE: 'Purpose',
            ACTIVE_VEHICLES: 'Total active vehicles',
            CUSTOMER_PROFILE: 'Customer Profile',
            CUSTOMER_DETAILS: 'customer details',
            SYSTEM_CONFIG: 'system configuration',
            SYSTEM_DISPATCHING_MODE: 'system dispatching mode',
            SYSTEM_DISTRIBUTION_MODE: 'system distribution mode',
            DISTRIBUTION_PLAN: 'distribution plan',
            MANUAL_DISPATCHING: 'manual dispatching',
            AUTOMATIC_DISPATCHING: 'automatic dispatching',
            MANUAL_PARAGRAPH: 'Manual dispatching : Enable all nearby vehicles to receive the on-demand pickup request for grabbing',
            AUTOMATIC_PARAGRAPH: 'Automatic dispatching : Assign the nearest vehicle to the on-demand pickup request',
            MANUAL_DISTRIBUTION: 'manual distribution',
            AUTOMATIC_DISTRIBUTION: 'automatic distribution',
            CONFIGURATION_ITEM: 'Configuration Item',
            VALUE: 'Value',
            UNIT: 'Unit',
            DESCRIPTION: 'Description',
            SELECT_COUNTRY: 'Select Country',
            SELECT_CITY: 'Select City',
            STREET_NAME: 'Street Name ',
            STREET: 'Street ',
            BUILDING_NUMBER: 'Building Number',
            WASEL_CODE: 'Wasel Code',
            LATITUDE: 'Latitude',
            LONGITUDE: 'Longitude',
            EDIT_BUILDING: 'Edit Building',
            AREA: 'Area',
            DELETE_BUILDING: 'Delete Building',
            DELETE_CONFIRMATION: 'Are you sure you want to delete?',
            DELETE: 'Delete',
            EDIT: 'Edit',
            RESCHEDULE: 'Reschedule',
            DELETE_USER: 'Delete User',
            EDIT_USER: 'Edit User',
            IMAGE: 'Image',
            LICENSE_TYPE: 'License Type',
            LICENSE_ID: 'License ID',
            LICENSE_EXPIRY_DATE: 'License Expiry Date',
            SELECT_VEHICLE_PURPOSE: 'Select Vehicle Purpose',
            SELECT_VEHICLE_TYPE: 'Select Vehicle Type',
            MODEL: 'Model',
            MOTOR_NO: 'Motor No.',
            COLOR: 'Color',
            WEIGHT_KG: 'Weight in (kg)',
            WIDTH: 'Width',
            HEIGHT: 'Height',
            LENGTH: 'Length',
            SELECT_BUILDING: 'Select Building',
            SELECT_BUILDING_TYPE: 'Select Building Type',
            CAPACITY: 'Capacity',
            EDIT_VEHICLE: 'Edit Vehicle',
            ITEMS_PER_PAGE: 'Items Per Page',
            DELETE_SCHEDULED_REQUEST: 'Delete Scheduled Request',
            PACKAGE_IMGS_HINT: 'Package Image/s (Add at least one image)',
            PACKAGE_LABELING: 'Package Labeling',
            EDIT_PACKAGE: 'Edit Package',
            SELECT_PACKAGE_TYPE: 'Select Package Type',
            SELECT_SHIPMENT_SERVICE: 'Select Shipment Service',
            SELECT_SUB_SHIPMENT_SERVICE: 'Select Sub Shipment Service',
            DELETE_PACKAGE: 'Delete Package',
            LEFT: 'left',
            RIGHT: 'right',
            OF: 'of',
            IMAGE_REQUIRED: 'Image is required ',
            REQUIRED: ' is required',
            INVALID: 'is invalid',
            SHORT: 'is too short',
            LONG: 'is too long',
            ENTER_NUM_ONLY: 'Enter Numbers Only',
            NUMBER: 'Number',
            MAX_CHARACTERS: 'maximum characters are {{number}}',
            MIN_CHARACTERS: 'minimum characters are {{number}}',
            MAX_NUMBERS: 'maximum numbers are {{number}}',
            MIN_NUMBERS: 'minimum numbers are {{number}}',
            FORMAT_error: 'use only letters (a-z), numbers, and periods',
            ADD_USER_SUCCESS_MSG: 'User has been added successfully ',
            DEL_USER_SUCCESS_MSG: 'User has been deleted successfully ',
            EDIT_USR_SUCCESS_MSG: 'User has been updated successfully ',
            ADD_BUILD_SUCC_MSG: 'Building has been added successfully ',
            DEL_BUILD_SUCC_MSG: 'Building Status has been changed successfully ',
            DEL_BUILD_ERR_MSG: 'Error in change Building Status',
            EDIT_BUILD_SUCC_MSG: 'Building has been updated successfully ',
            ERROR_BUILD: 'Building already deleted',
            ERROR_BUILDS: 'Building(s) already deleted',
            ERROR_BUILDS_WITH_VEH: 'Building cannot be deleted as vehicles Or Users are assigned to it',
            GENERAL_DEL_ERROR: 'Some record(s) already deleted',
            NO_INTERNET: 'An unexpected error has occured. It may be due to Internet connection. Please check your connection or contact the Administrator.',
            ERROR_USER: 'User already deleted',
            ERROR_USERS: 'User(s) already deleted',
            ADD_PACKAGE_SUCC_MSG: 'Package has been added successfully',
            DEL_PACKAGE_SUCC_MSG: 'Package has been deleted successfully',
            EDIT_PACKAGE_SUCC_MSG: 'Package has been updated successfully',
            ERROR_PACKAGE: 'Package already deleted',
            ERROR_PACKAGES: 'Package(s) already deleted',
            DEL_REQ_SUCC_MSG: 'Request has been deleted successfully',
            FAIL_PACKAGE: 'Failed to load package details',
            FAIL_REQ: 'Failed to load request details',
            EDIT_PICKUP_SUCC_MSG: 'Pickup request has been updated successfully',
            ADD_VHCL_SUCC_MSG: 'Vehicle has been added successfully ',
            DEL_VHCL_SUCC_MSG: 'Vehicle has been deleted successfully ',
            EDIT_VHCL_SUCC_MSG: 'Vehicle has been updated successfully',
            ERROR_VHCL: 'Vehicle already deleted',
            ERROR_VHCLS: 'Vehicle(s) already deleted',
            FAIL_USER: 'Failed to load user data',
            AWESOME: 'Awsome..',
            WARNING: 'Warning..',
            OH_NO: 'Oh no!',
            MAX_DIMEN: 'max dimension:-',
            MAX_WEIGHT: 'max weight:-',
            AT_LEAST_ONE_IMG: 'At least one image',
            INVALID_NUMBER: 'invalid number',
            BIG_NUMBER: 'is big number',
            BIGGER_THAN_STANDARD: 'is bigger than standard',
            LESS_THAN_STANDARD: 'is less than standard',
            INVALID_ID: 'Invalid ID',
            TO_REQUEST_DATE: 'Date interval',
            TO_PICKUP_DATE: 'Date interval',
            ADD_IMAGE: 'Add Image',
            REMOVE_IMAGE: 'Remove Image',
            PACKAGE_IMG: 'Package Image',
            PACKAGE_DEF_IMG: 'Package Default Image',
            USER_IMG: 'User Image',
            USER_DEF_IMG: 'User Default Image',
            PACKAGE_FIRST_IMG: 'Package First  Image',
            PACKAGE_2nd_IMG: 'Package Second  Image',
            IMG_TOO_LARGE: 'Image is too large',
            FILE_NOT_IMG: 'File is not an image',
            FILE_NOT_SUPP: 'File is not supported',
            FILE_IS_DUPLICATED: 'File is duplicated',
            FILE_CORRUPTED: 'File is corrupted',
            IMAGE_UPLOAD_ERR: 'Image(s) cannot upload',
            DATE_FORMAT: 'dd/MM/yyyy',
            KG: 'kg',
            PM: 'PM',
            AM: 'AM',
            MM: 'MM',
            HH: 'HH',
            SAVE: 'Save',
            REMOVE: 'Remove',
            ADD_ROLE: 'add role',
            ROLE_NAME: 'Role Name',
            ROLE_DES: 'Role Description',
            ACTIVATION: 'Activation',
            MODULE_NAME: 'Module Name',
            SET_PERMISSIONS: 'set permissions',
            PERMISSIONS: 'Permissions',
            VIEW: 'View',
            EDIT_ADD: 'Add/Edit',
            ACTIVE_DEACTIVATE: 'Activate/Deactivate',
            ASSIGN_USER: 'assign user',
            CANCLE: 'Cancel',
            SERCH_USER: 'Search for user',
            NO_USER_ASSIGNED: 'No User Assigned',
            TOTAL_PICKUPS: 'Total pickups',
            TOTAL_DELIVERIES: 'Total deliveries',
            EDIT_ROLE: 'edit role',
            IMG_CNOT_UPLOD: "image(s) cannot upload",
            DEVICES: 'devices',
            ADD_DEVICE: 'Add Device',
            PHONE_NUMBER: 'Phone Number',
            PRIVILEGE_ERROR: 'Something wrong happened .. try to connect later',
            DEACTIVATE_SELECTED: 'Deactivate Selected',
            DEL_DEVICE_SUCC_MSG: 'Device status changed successfully',
            DEL_DEVICE_ERR_MSG: 'Error in change device status',
            IMEI: 'IMEI',
            EDIT_DEVICE: 'Edit Device',
            DRIVER_NAME: 'Driver Name',
            DRIVER_NUMBER: 'Driver Number',
            JOB_ID: 'Job ID',
            CUSTOMER_NAME: 'Customer Name',
            CUSTOMER_NUMBER: 'Customer Number',
            JOB_STATUS: 'Job Status',
            PICKUP_MAP_SUMMARY: '{{number}} out of {{total}} are picked up',
            DILEVERY_MAP_SUMMARY: '{{number}} out of {{total}} are delivered',
            ACTIVE_VEHICLE: 'active vehicles',
            ADD_ACTIVE_VEHICLE: 'Add Active Vehicle',
            DEVICE_ID: 'Device ID',
            ADD_DEVICE_SUCC_MSG: 'Device has been added successfully',
            EDIT_DEVICE_SUCC_MSG: 'Device has been updated successfully',
            SELECT_BRAND: 'Select Brand',
            REMOVE_ASS_BTN: 'Remove Assigned User',
            RETURN_HOME: 'Return Home',
            ERROR_401: 'OOPS! You are not authorized to go to this page.',
            ERROR_404: 'OOPS! Not found.',
            ERROR_404_msg: 'The page you requested was not found',
            ERROR_500: 'Sorry! Internal Server Error',
            ERROR_500_msg: 'Something went wrong try again in a moment',
            CHASSIS: 'Chassis',
            MULTISTOP: 'Multi Stop',
            PICKUP: 'Pickup',
            PICKUP_DELIVERY: 'Pickup & Delivery',
            PASSWORD: 'Password',
            DELETE_ACTIVE_VEHICLE: 'Delete Active Vehicle',
            SELECT_VEHICLE: 'Select Vehicle ID',
            SELECT_DRIVER: 'Select Driver Name',
            SELECT_DEVICE: 'Select Device ID',
            SELECT_WORKSHIFT: 'Select Work Shift',
            SELECT_CALENDER: 'Select Calender',
            SELECT_RETURN_ADDRESS: 'Select Return Address',
            VEHICLE: 'Vehicle',
            DEVICE: 'Device',
            DRIVER: 'Driver',
            CALENDER: 'Calender',
            WORKSHIFT: 'Work Shift',
            DEL_ACTIVE_VEHICLE_SUCC_MSG: 'Active Vehicle has been deleted successfully',
            SIZE: 'Size',
            CORRESPONDENCE: 'Correspondence Weight in Kg',
            ADD_PACKAGE_WEIGHT: 'Add Package Weight',
            ADD_PW_SUCC_MSG: 'Package Weight has been added successfully',
            NEW: 'New',
            SCHEDULED_FOR_PICKUP: 'Scheduled for pickup',
            AWAITING_PICKUP: 'Awaiting Pickup',
            WAITING_FOR_CUSTOMER_ALTERNATIVE: 'Waiting for customer',
            ACTION_NEEDED: 'Action needed',
            IN_PICKUP_VERIFICATION: 'In pickup verification',
            IN_DELIVERY_VERIFICATION: 'In delivery verification',
            PICKEDUP: 'Picked up',
            CANCELED: 'Canceled',
            AVAILABLE_ACTIVE_VEHICLES: 'Available Active Vehicles',
            SCHEDULED_JOB_ORDERS: "scheduled job orders",
            JOB_ORDERS_DISTRIBUTION: "distribute job orders",
            CLEAR_ALL: "Clear all",
            VERIFY: "Verify",
            ASSIGN: 'assign',
            POINTERROR_A: 'building location not defined',
            POINTERROR_B: 'building located in other building areas',
            POINTERROR_C: 'building location out of selected area',
            POLYGONERROR_A: 'define area borders',
            POLYGONERROR_B: 'building area Intersected with other building',
            DRAWPOLYGON: 'Draw Served area',
            ADDMARKER: 'Add Marker',
            REM_POL_MAR: 'Remove Served Area',
            CHK_PNT_MTCH: 'Check Point Match',
            CHK_PLGN_MTCH: 'Check Served Area',
            ROLE_S: 'Roles',
            SOME_REQ_EXIST: 'There is request(s) assigned to this vehicle',
            DEACTIVE_CONFIRMATION: 'Are you sure you want to deactivate this vehicle',
            DEACTIVATE_VHCL_SUCC_MSG: 'Active Vehicle has been deactivated successfully',
            DEACIVATE_ACTIVE_VEHICLE: 'Deactivate Active Vehicle',
            ASSIGN_ORDER: 'Assign Order',
            CALENDAR: 'Calendar',
            CALENDAR_CONFIG: 'Calendar Config',
            JOB_DISTRIBUTION: 'job distribution',
            DEVICE_MODEL: 'Device Model',
            SLCT_DEVICE_MODEL: 'Select Device Model',
            CANCEL_ONDEMAND_SUCC_MSG: 'Request has been canceled successfully',
            SCHEDULE_REQUEST: 'Schedule request',
            SCHEDUL_ONDEMAND_SUCC_MSG: 'Request has been scheduled successfully',
            CONFIRM_CANCELLATION: 'Confirm Cancellation',
            CONFIRM_MSG_CANCELLATION: 'Are you sure you want to cancel request?',
            SELECT_CANCELLATION_REASON: 'Select Predefined cancellation reason',
            ADDITIONAL_NOTES: 'Additional Notes',
            CONFIRM: 'Confirm',
            SCHEDULE: 'Schedule',
            SEND_NOTIFICATION: 'Send Notification',
            CANCEL_REQUEST: 'Cancel Request',
            SEND_NOTIFICATION_SUCC_MSG: 'Notification sent Successfully',
            CANCELLATION_REASON: 'Cancellation Reason',
            ADD_ACTIVE_VEH: 'Add Active Vehicle',
            ERROR_DRIVER_WITH_VEH: 'Driver(s) already related with active vehicle(s)',
            ERROR_VEH_WITH_VEH: 'Vehicle(s) already related with active vehicle(s)',
            ERROR_DIVICE_WITH_VEH: 'Device(s) already related with active vehicle(s)',
            SET_WORKING_DAYS: 'set working days',
            SET_WORKING_SHIFTS: 'set working time shifts',
            SET_SEL_DAY_W_N: 'Set selected day to be working or non-working',
            SET_WORK: 'Set day(s) to working day(s)',
            SET_NON_WORK: 'Set day(s) to nonworking day(s)',
            ADD_MORE: 'Add more',
            SHIFT_OCCURS: 'Shift occurs on existing shift',
            ENTER_DATE: 'Work shift time is invalid',
            SHIFT_LESS: 'shift to is less than or equal from',
            SATURDAY: 'saturday',
            SUNDAY: 'sunday',
            MONDAY: 'monday',
            TUESDAY: 'tuesday',
            WEDNESDAY: 'wednesday',
            THURSDAY: 'thursday',
            FRIDAY: 'friday',
            DEF_UP_6: 'Define up to 6 work shift per day',
            WORKING_DAYS: "working days",
            NON_WORKING_DAYS: "non-working days",
            ADD_SHIFT: "Add Work Shifts",
            APPLY_CONFIRMATION: 'Shifts will effect active vehicle table are you sure to apply?',
            CHANGE_SHIFT: 'Change Shift',
            REMAINING_ORDERS: "remaining Orders",
            ETA: "ETA",
            PICKUP_REQUESTS: "Pickup Requests",
            ON_DEMAND_PICKUPS: "On Demand Pickup",
            SCHEDULE_PICKUPS: "Schedule Pickups",
            DISPATCH_ACTIVITIES: "Dispatch Activities",
            ACTIVE_JOBS: "Active Jobs",
            VEHICLE_MAP_VIEW: 'Vehicle Map View',
            BUILDINGS_MAP_VIEW: 'Building Map View',
            SYSTEM_FEATURES: 'System Features',
            USERS_MANAGEMENT: 'Users Management',
            ROLES_PERMISSIONS: 'Roles & Permissions',
            WORK_CALENDAR: 'work calendar',
            USER_TYPE: 'User Type',
            SUCC_ADD_ROLE: 'Roles has been assigned successfully',
            DRIVER_RESPONSE: 'driver response',
            ACCEPTED: 'accepted',
            ACCEPT: 'Accept',
            REJECTED: 'rejected',
            REJECT: 'reject',
            REASSIGN: 're-assign',
            REASSIGN_ALL: 're-assign all',
            NO_ASSGINED_ORDERS_OV: 'No vehicles have assigned orders',
            LOADING_ACTVITIES: 'Loading Activities',
            ADMINSTRATE: 'Administrate',
            SET_ROLE: 'set role',
            SET_ROLES: 'Set Roles',
            MINS: " mins",
            ACTIVE_VEHICLE_ID: 'Active Vehicle ID',
            BOX: 'Box',
            DOCUMENT: 'Document',
            RECEIVED_FROM_HH_MM: 'Received From (hh:mm)',
            DRIVER_RATING: 'driver rating',
            DRIVERS_RATING: 'drivers rating',
            ADD_ROLE_HINT: 'Select roles to be added to selected users',
            SELECT_ROLE: 'Select Role',
            SCHEDULE_REQUEST_CAP: 'SCHEDULE REQUEST',
            BACK_OFFICE_EMPLOYEE: 'Back office',
            BACK_OFFICE: 'Back office',
            DUPLICATED_USER_MSG: 'User already exist',
            EDIT_ROLE_MSG_SUCC: 'Role has been updated successfully',
            ADD_ROLE_SUCC_MSG: 'Role has been added successfully',
            HELLO: 'Hello ',
            THIS_DASHBOARD: 'This Dashboard',
            REASON_ONE: 'Reason one',
            REASON_TWO: 'Reason two',
            REASON_THREE: 'Reason three',
            SUCCESS: "success",
            IN_GRACE_PERIOD: "in grace period",
            FAIL: "failure",
            STARTS_AT: "starts at",
            CASH: 'cash',
            CANCEL_ONDEMAND_ERR_MSG: 'Request was already canceled',
            USER_CANCEL: 'User cancel',
            ERR_ASSIGN_DRI: 'Error in assigning roles to driver(s)',
            ACTIVE_ORDERS: 'active orders',
            VEH_ASSIGN_SUCC_MSG: 'Vehicle assigned successfully',
            DELIVERY_REQUESTS: 'delivery requests',
            REQUESTS: 'Requests',
            DELIVERY_SCHEDULED_FOR: 'Delivery Scheduled For ',
            DELIVERY_DATE: 'Delivery Date',
            DELIVERY_TIME: 'Delivery Time',
            CREDIT_CARD: 'Credit Card',
            PACKAGE_VERIFICATION: 'Package Verification',
            VERIFICATION_BY_DRIVER: 'verification by driver',
            ASSIGNED: 'Assigned',
            VEHICLE_OVERWEIGHT: "vehicle overwight",
            PLAN_SUBMIT_SUCC: "plan successfully submitted",
            TRACKING_NUMBER: "Tracking Number",
            PACKAGE_STATUS: "Package Status",
            SCHEDULED_FOR_DELIVERY: 'Scheduled for delivery',
            DELIVERED: 'Delivered',
            RESCHEDULE_FOR_RETURN: 'Reschedule for return',
            RESCHEDULED_FOR_RETURN: 'Rescheduled for return',
            RE_SCHEDULED_FOR_PICKUP: 'Rescheduled for pickup',
            RESCHEDULED_FOR_DELIVERY: 'Rescheduled for delivery',
            RESCHEDULED: 'Rescheduled',
            DELIVERY_REQUEST_DETAILS: 'delivery request details',
            EDIT_DELIVERY_SUCC_MSG: 'Delivery request has been reschduled successfully',
            VEHICLE_STATE: 'Vehicle State',
            STARTS_FROM: 'Starts From',
            DESTINATION: 'Destination',
            PICKUPS_STATUS: 'Pickups Status',
            DELIVERY_STATUS: 'Delivery Status',
            ACTIVE_ORDER: 'active order',
            VEHICLE_BRAND: 'Vehicle Brand',
            VEHICLE_COLOR: 'Vehicle Color',
            VEHICLE_MODEL: 'Vehicle Model',
            ORDERS_IN_QUEUE: 'Orders in queue',
            ARRIVAL_TIME_INTERVAL: 'Arrival Time Interval',
            OUT_FOR_DELIVERY: 'Out for delivery',
            RETURNED: 'Returned',
            CANCELLED: 'Cancelled',
            VEH_RELATED: 'Vehicle Related to active plan',
            OUT_OF: 'out of',
            SCHEDULED_FOR_RETURN: 'scheduled for return',
            RETURN_ADDRESS: 'Return Address',
            SENDER_ADDRESS: 'Sender Address',
            SENDER_MOBILE: 'Sender Mobile',
            RETURN_DATE: 'Return Date',
            DEVICE_NUMBER: 'Device Number',
            CITY: 'City',
            DIFFRENT_ADDRESS: 'Diffrent Address',
            RETURN_LOCATION: 'Return Location',
            RESCHEDULE_FOR_RETURN_SUCCESS: 'reschedule for return success',
            EXISTING_PLAN: 'Another plan already exists',
            RETURN_REQUESTS: 'return requests',
            PLAN_DETAILS: 'plan details',
            REPLAN: 'replan',
            CREATED_AT: 'created at',
            SUBMITTED_AT: 'submitted at',
            FAQ: 'FAQ',
            ADD_FAQ: 'Add FAQ',
            EDIT_FAQ: 'Edit FAQ',
            LANGUAGE: 'Language',
            SELECT_LANGUAGE: 'Select Language',
            ARABIC: 'Arabic',
            ENGLISH: 'English',
            QUESTION: 'Question',
            ANSWER: 'Answer',
            RETURN_REQUEST_DETAILS: 'Return Request Details',
            ADD_FAQ_SUCCESS_MSG: 'FAQ has been added successfully ',
            FREQ_ASK_QUES: 'Frequently Asked Questions',
            N_A: "N/A",
            ACTIVE_ORDER_IN_PROGRESS: 'Active Order In-progress',
            ASSI_DRIV_VEH_DET: 'Assigned driver and Vehicle Details',
            CANT_LOAD_MAP: 'cannot load map currently',
            IN_RETURN_VERIFICATION: 'In Return Verification',
            DELETE_FAQ: 'Delete FAQ',
            "ON-DEMAND": 'On-demand',
            FRENCH: 'French',
            CONFIRM_PASSWORD: "Confirm Password",
            PASSWORD_CHANGED_SUCCESS: "Your Password Has Been Successfully Changed",
            EMAIL_SUCCESS_SENT: "Email Successfully Sent",
            DOMESTIC: "domestic",
            NEXTDAY: "next day",
            SCHEDULED: "scheduled",
            CHANGE_PASSWORD: "change password",
            NEW_PASSWORD: "New Password",
            OLD_PASSWORD: "Old Password",
            PASSWORDS_DONT_MATCH: "Passwords don't match",
            EDIT_PROFILE: "edit profile",
            TO_DELIVERY_DATE: "Date Interval",
            RECIP_ADDRESS: 'Recipient Address',
            USER_CANCELED: 'User Canceled',
            ON_DEMAND_DETAILS: 'On Demand Request Details',
            SCHEDULED_DETAILS: 'Scheduled Request Details',
            CREATED_BY: "created by",
            CREATED_FROM: "created from",
            DRIVER_RESPONSE_TIME: 'driver response time',
            DISPATCH_MODE: 'dispatch mode',
            NEARBY_VEHICLES_RANGE: 'nearby vehicles',
            TRIALS_OF_LOOKING_FOR_VEHICLE: 'trails of looking for vehicle',
            TRIALS_INTERVAL_OF_LOOKING_FOR_VEHICLE: 'trails interval of looking for vehicle',
            WAITING_TIM_F_STTS_LKN_F_VEH: 'waiting time for status of looking for vehicle',
            TRIALS_INTRV_F_STTS_LKN_F_VEH: 'trials interval for status of looking for nearby vehicle',
            EMERGENCY_CAPACITY: 'emergenct capacity',
            DISTRIBUTION_MODE: 'distribution mode',
            AUTOMATIC_PLAN_CREATION_TIME: 'automatic plan creation time',
            COUNT_DOWN: 'count down',
            LATE_TIME_INTERVAL: 'late time interval',
            EARLY_TIME_INTERVAL: 'early time interval',
            START_TIME_INCREMENT_FACTOR: 'start time increment factor',
            REQUEST_PROCCESSING_TIME: 'request preccessing time',
            GRACE_PERIOD_TIME: 'grace period time',
            C_COUNT_DOWN_DESC: 'count down for radar',
            C_DRIVR_RESPNS_TIME_DESC: 'the maximum time given to the driver to grab any on-demand pickup request.The maximum time given to the driver to grab any on-demand pickup request.The maximum time given to the driver to grab any on-demand pickup request.The maximum time given to th',
            C_NEAR_VEH_RANG_DESC: 'a diameter from the pickup-location upon which a vehicle can be defined as nearby',
            C_TRAILS_LKN_F_VEH_DESC: 'number of trails the system conduct to look for vehicle for on-demand pickup request',
            C_TRLS_INTRV_F_LKN_VEH_DESC: 'time interval between trails the system conduct to look for vehicle for on-demand pickup request',
            C_WTNG_TIM_F_STTS_LKN_F_VEH_DESC: 'the time the system will keep looking for vehicle',
            C_TRLS_INTRV_F_STTS_LKN_F_VEH_DESC: 'time interval between trails the system conduct to look for nearby vehicle',
            C_EMRGNCY_CAP_DESC: 'the percent of minimum availabe capacity in vehicle',
            C_ATMTC_PLN_CRTION_TIM_DEC: 'time of creating automatic distribution plan',
            C_LATE_TIME_INTERVAL_DESC: 'late time interval',
            C_EARLY_TIME_INTERVAL_DESC: 'early time interval',
            C_START_TIME_INCREMENT_FACTOR_DESC: 'start time increment factor',
            C_REQUEST_PROCCESSING_TIME_DESC: 'request proccessing time',
            C_GRACE_PERIOD_TIME_DESC: 'grace period time',
            BASIC_INFO: 'Basic info',
            CANCEL: 'Cancel',
            CHANGE: 'Change',
            CHANGE_EMAIL: 'change email',
            CHANGE_EMAIL_SUCCESS: 'email changed successfully',
            ACCOUNT_DETAILS: 'account details',
            SENDER_PHONE: 'Sender Phone',
            RECIPIENT_PHONE: 'Recipient Phone',
            OUT_FOR_RETURN: 'Out For Return',
            KM: 'km',
            SECOND: 'second',
            HRS: 'hrs',
            TRIALS: 'trials',
            PERCENT: 'percent',
            ON_DEMAND_SERVICES: 'on demand services',
            SCHEDULED_SERVICES: 'scheduled service',
            TRANSIT_SERVICES: 'transit service',
            CHECK_YOUR_PASSWORD: 'please check your password',
            PROGRESS: 'progress',
            AVAILABLE: 'available',
            NEW_RETURN: 'New Return',
            CANCELED_DELIVERY: 'Canceled Delivery',
            ON_ROUTE: 'On Route',
            ON_BREAK: 'On Break',
            BUSY: 'Busy',
            NO_VEHICLES: 'no vehicles',
            NO_COVERAGE: 'no coverage',
            NOCOVERAGE: 'no coverage',
            NO_CAPACITY: 'no capacity',
            NOCAPACITY: 'no capacity',
            COUNTRY_CODE: 'country code',
            SELECT_COUNTRY_CODE: 'Select country code',
            ADVANCED_SEARCH: 'Advanced Search',
            APPLY: 'APPLY',
            RESET_FILTER: 'RESET',
            DELETE_RETURN_REQUEST: 'Delete return request',
            HUB_ADMIN: 'Hub Admin',
            CORPORATE_DRIVER: 'Corporate Driver',
            HUB_NAME: 'Hub Name',
            FREELANCER_ADMIN: 'Freelancer Admin',
            SUPERVISOR: 'Supervisor',
            OPERATION_BACKOFFICE: 'Operational back-office',
            OFFLOADING: 'offloading',
            TOTAL_PACKAGES: 'total packages',
            FREELANCER_REQUESTS: 'Freelancer Requests',
            LAUNCH_CITY: 'Launch City',
            VEHICLE_STATUS: 'Vehicle Status',
            FREELANCER_DETAILS: 'Freelancer Details',
            CITY_TO_DRIVE_IN: 'City to drive in',
            DRIVERS_LICENSE: "Driver's license",
            YEAR: 'Year',
            PLATE_NUMBER: 'Plate number',
            TYPE: 'Type',
            MOTOR_NUMBER: 'Motor number',
            WEIGHT: 'Weight',
            CHASSIS_NUMBER: 'Chassis number',
            VEHICLE_OWNERSHIP_ID: 'Vehicle ownership ID',
            CRIMINAL_RECORDS: 'Criminal records',
            BIRTH_CERTIFICATE: 'Birth certificate',
            REPORT_MISSING_DOCUMENTS: 'Report missing documents',
            DOCUMENTS: 'Documents',
            MISSING_DOCUMENTS_REPORTED: 'Missing documents reported', //
            FREELANCER_REJECTED: 'Freelancer has been rejected', //
            FREELANCER_ACCEPTED: 'Freelancer has been accepted', //
            ACCEPT_PACKAGE_OFFLOADING: 'Are you sure you want to accept?', //
            REPORT_PACKAGE_OFFLOADING: 'Are you sure you want to report?', //
            UNDO_PACKAGE_OFFLOADING: 'Are you sure you want to undo?', //
            ALL_BUILDINGS: 'all buildings',
            OPERATIONS_RANKS: 'operations ranks',
            CUSTOMERS_AGE: 'customers age',
            SUCCEEDED: 'Succeeded',
            MODERATE: 'moderate',
            LOW: 'low',
            EXTREMELY_BUSY: 'extremely busy',
            CORPORATE: 'corporate',
            ALL: 'all',
            ONESTARS: '1 stars',
            TWOSTARS: '2 stars',
            THREESTARS: '3 stars',
            FOURSTARS: '4 stars',
            FIVESTARS: '5 stars',
            GO_EXTRA: 'go extra',
            SEVEN_DAYS: 'last 7 days',
            THIRTY_DAYS: 'last 30 days',
            PACKGESLESSTHAN5KG: 'less than 5Kgs',
            PACKGESLESSTHAN10KG: 'less than 10Kgs',
            PACKGESLESSTHAN25KG: 'less than 25Kgs',
            FREELANCERDRIVER: 'freelancer driver',
            AGEBETWEEN21AND30: 'Age between 21 to 30',
            LESSTHAN21: 'Age less than 21',
            AGEBETWEEN31AND45: 'Age between 31 to 45',
            AGE_ABOVE_45: 'Age above 45',
            OTHERAGES: 'Others',
            OTHERS: 'Others',
            MINUTES: 'minutes',
            AVG_TIME_AT_CUSTOMER_PICK: 'avg time spent at customer at pickups',
            PACKAGE_CATEGORY: 'Package category',
            RECEIVE: 'Receive',
            REPORT_MISSING: 'Report Missing',
            VEH_STATUS_CHAN_SUCC: 'Vehicle Status Changed Successfully',
            EMP_STATUS_CHAN_SUCC: 'Employee Status Changed Successfully',
            VEH_STATUS_NOT_CHAN_SUCC: 'error in change vehicle status',
            AMOUNT: 'Amount',
            IN_TODAYS_PLAN: 'in todays plan',
            OFFLOADING_ACTIVITIES: 'offloading activities',
            CONFIGURATION: 'Configuration',
            BUILDING_CONFIG: 'building configuration',
            MOBILE_CONFIG: 'mobile configuration',
            ON_DEMAND_CONFIG: 'on demand configuration',
            DISTRIBUTION_CONFIG: 'distribution',
            GENERAL_OPERATIONS: 'general operations',
            CONTACT_US: 'contact us',
            HOTLINE_TITLE: 'hotline title',
            HOTLINE_NUMBER: 'hotline number',
            CONTACT_US_FOR_CUS_APP: 'contact us for customer app',
            EMAIL_ADD_TITLE: 'email address title',
            DAILY_WORKING_HOURS: 'Daily Working Hours',
            VACATION_WORKING_HOURS: 'Vacation Working Hours',
            DAILY: 'daily',
            MOBILE_CONFIGURATION: 'mobile configuration',
            CONTACTUS_SAVED_SUCCESS: 'contact us saved successfully',
            IN_DISTRIBUTION: 'in distribution',
            PENDING: 'Pending',
            BACK_CUSTOMER_LIST: 'Back to customer list',
            STATISTICS: 'Statistics',
            CUSTOMER_REQUESTS: 'Customer Requests',
            PROCESSED: 'Processed',
            CUSTOMER_USED_CATEGORY: 'Most Used Category',
            ARCHIVED_DELIVERY: 'Archived Delivery',
            ARCHIVED_RETURNS: 'Archived Returns',
            RANKING: 'ranking',
            TOTAL_OPERATIONS: 'total operations',
            IN_PROGRESS: 'In progress',
            NO_CATEGORIES: 'No Categories',
            PICKUP_HISTORY: 'Pickup History',
            DELIVERY_HISTORY: 'Delivery History',
            RETURN_HISTORY: 'Return History',
            REQUEST_TIME: 'Request Time',
            PICKUP_TIME: 'Pickup Time',
            IMAGES: 'Images',
            RETURN_TIME: 'return time',
            ARCHIVED_PICKUPS: 'Archived Pickups',
            ORDERS: 'orders',
            ENDED: 'ended'
        });
        $translateProvider.translations('ar', {
            SEARCH: 'بحث',
            SUMMARY: 'تقرير ملخص',
            SUBMIT: 'تطبيق',
            ADD_USER: 'إضافه عميل',
            FIRST_NAME: 'الاسم الاول ',
            LAST_NAME: 'الاسم الاخير ',
            MOBILE_NUMBER: ' رقم الهاتف ',
            EMAIL_ADDRESS: ' البريد الالكترونى',
            NATIONAL_ID: 'رقم البطاقه ',
            SELECT_USER_TYPE: 'اختيار نوع العميل ',
            DESCRIPTION_OPTIONAL: 'وصف ..(إختيارى)',
            BUTTON_LANG_EN: 'English',
            BUTTON_LANG_AR: 'العربيه',
            BUILDING_LIST_TITLE: 'مبنى',
            ADD_BUILDING: 'اضف مبنى',
            CLEAR_BTN: 'محو الاختيار',
            CLEAR: 'محو',
            DELETE_BTN: 'حذف الاختيار',
            BUILDING_ID: 'رقم المبنى',
            BUILDING_TYPE: 'نوع المبنى',
            BUILDING_NAME: 'اسم المبنى',
            BUILDING_COUNTRY: 'الدوله ',
            BUILDING_CITY: 'المدينه ',
            ACTIONS: 'إجراءات',
            FILTER: 'فلتر',
            DASHBOARD: 'الصفحة الرئيسيه',
            LOADING_ACTIVITIES: 'انشطه',
            MAPS: 'خرائط',
            PICKUPS: 'الإلتقاط',
            DELIVERABLE: 'معطيات',
            HUB_MANAGEMENT: 'إداره المبانى',
            PACKAGES: 'الشحنات',
            PACKAGE: 'الشحنه',
            TRACKING_PACKAGES: 'متابعة الشحنات',
            CUSTOMERS: 'الزبائن',
            REPORTS: 'التقارير',
            USER_FEATURES: 'خصائص العضو',
            ON_DEMAND_REQUESTS: 'الطلبات الفوريه',
            SCHEDULE_REQUESTS: 'طلبات بالجدول',
            HISTORY_PICKUP: 'تاريخ الالتقاطات',
            USERS: 'العملاء',
            ROLES: 'قائمة الوظائف',
            BUILDINGS: 'المبانى',
            VEHICLES: 'الشاحنات',
            CITY_VIEW: 'نظره المدينه',
            VEHICLE_VIEW: 'نظره السياره',
            ARCHIVED_REQUESTS: 'تطلب من الأرشيف',
            OPERATION_CENTER: 'مركز العمليات',
            DELIVERY: 'التوصيل',
            RETURN: 'استرجاع',
            FILTER_VEHICLE: 'ابحث باسم السيارة',
            OPERATION_CENTER_SEARCHBY: 'اختر مركز العمليات',
            AVALIABLE_VEHICLE: 'السيارات المتاحه',
            BUSY_VEHICLE: 'السيارات المشغوله',
            PROFILE: 'الصفحة الشخصية',
            PROFILE_SUCCESS_UPDATE: 'تم تحديث الصفحه الشخصيه بنجاح',
            LOCK_USER: 'اغلق الشاشة',
            SIGN_OUT: 'خروج',
            COPY_RIGHTS: 'جميع الحقوق محفوظة لشركة',
            TODAY: 'اليوم',
            RESET: 'اعادة',
            ON_DEMAND_PICKUP_REQUESTS: 'طلبات الالتقاط الفوريه',
            ID: 'الرقم',
            PICKUP_CITY: 'المدينة',
            PICKUP_AREA: 'المنطقة',
            PACKAGE_TYPE: 'نوع الشحنة',
            PICKUP_TYPE: 'نوع الالتقاط',
            PACKAGE_WEIGHT: 'وزن الشحنة',
            RECEIVED_FROM: 'أرسلت من',
            REQUEST_STATUS: 'حالة الطلب',
            SCHEDULED_PICKUP_REQUEST: 'طلبات الالتقاط المجدوله',
            REQUEST_ID: 'رقم الطلب',
            REQUEST_TYPE: 'نوع الطلب',
            REQUESTS_TYPES: 'أنواع الطلابات',
            REQUEST_MOBILE: 'رقم هاتف الطالب',
            FROM: 'من',
            TO: 'إلى',
            REQUEST_DATE: 'تاريخ الطلب',
            PICKUP_DATE: 'تاريخ الالتقاط',
            APPLY_FILTRATION: 'طبق البحث',
            RESET_DATA: 'محو البيانات',
            TIME_INTERVAL: 'الفترة الزمنية',
            RETURN_TIME_INTERVAL: 'الفتره الزمنيه للرجوع',
            TOTAL_REQUESTS: 'مجموع الطلبات',
            STATUS: 'الحالة',
            ON_DEMAND_PICKUP_DETAILS: 'تفاصيل الطلبات الفورية',
            SCHEDULED_PICKUP_DETAILS: 'تفاصيل الطلبات المجدوله',
            REQUEST_DETAILS: 'تفاصيل الطلب',
            REQUESTER_ID: 'رقم الطالب',
            REQUESTER_NAME: 'اسم الطالب',
            SENDER: 'الراسل',
            SENDER_NAME: 'اسم الراسل',
            REQUEST_TIME_UTC: 'وقت الطلب بتوقيت غرينتش',
            PICKUP_DETAILS: 'تفاصيل الالتقاط',
            PICKUP_ADDRESS: 'عنوان الالتقاط',
            PICKUP_TIME_UTC: 'وقت الالتقاط بتوقيت غرينتش',
            PACKAGE_DETAILS: 'تفاصيل الشحنه',
            PACKAGE_ID: ' رقم الشحنه',
            PACKAGE_NICKNAME: 'اسم الشحنه المستعار',
            PACKAGE_WEIGHT_KG: 'وزن الشحنه  (كج)',
            PACKAGE_DIMENSION_CM: 'أبعاد الشحنه  (سم)',
            PACKAGE_DIMENSION: 'أبعاد الشحنه  ',
            PACKAGE_CONTAINER_LABELING: 'عنوان حاوية الشحنه',
            PACKAGE_BRIEF: 'تلخيص للشحنه',
            SHIPPING_RECIPIENT_DETAILS: 'تفاصيل الشحن و الاستقبال',
            SHIPPING_SERVICE: 'خدمة الشحن',
            SUB_SHIPPING_SERVICE: 'خدمة شحن فرعية',
            RECIPIENT_FULL_NAME: 'اسم المستقبل الكامل',
            RECIPIENT_NAME: 'اسم المستقبل',
            RECIPIENT_MOBILE_NUMBER: 'رقم هاتف المستقبل',
            RECIPIENT_ADDRESS: 'عنوان المستقبل',
            RECIPIENT: 'المسقبل',
            ADDITIONAL_INFORMATION: 'معلومات اضافيه',
            PAYMENT_DETAILS: 'تفاصيل الدفع',
            PAYMENT_AT: 'الدفع عند',
            PAYMENT_METHOD: 'الية الدفع',
            ADDITIONAL_SERVICES: 'خدمات إضافيه',
            WRAP_LABEL: 'التغليف و الاسم',
            PACKAGING_BOX: 'صندوق الشحن',
            PICKUP_SCHEDULED_FOR: ' الالتقاط المجدول فى',
            WITH_TIME_INTERVAL: 'للفترة الزمنيه  ',
            ADD_PACKAGE: 'أضف شحنه',
            GROUP_NAME: 'اسم المجموعة',
            UDER_ID: 'رقم العميل',
            FULL_NAME: 'الاسم الكامل',
            TOTAL_CUSTOMER: 'مجموع الزبائن',
            ADDRESS: 'العنوان',
            ADD_VEHICLE: 'أضف شاحنه',
            VEHICLE_ID: 'رقم الشاحنة',
            VEHICLE_TYPE: 'نوع الشاحنة',
            VEHICLE_MOTOR: 'موتور الشاحنة',
            VEHICLE_PLATE_NO: 'رقم لوحى الشاحنه',
            BRAND: 'العلامة التجارية',
            PLATE_NO: 'رقم اللوحه',
            PURPOSE: 'الغرض',
            ACTIVE_VEHICLES: 'السيارات الفعاله',
            CUSTOMER_PROFILE: 'صفحة الشخصية',
            CUSTOMER_DETAILS: 'بيانات الزبائن',
            SYSTEM_CONFIG: 'إعدادات النظام',
            SYSTEM_DISPATCHING_MODE: 'وضع إفاد المهام',
            SYSTEM_DISTRIBUTION_MODE: 'وضع توزيع المهام',
            DISTRIBUTION_PLAN: 'خطه التوزيع',
            MANUAL_DISPATCHING: 'إفاد يدوى',
            AUTOMATIC_DISPATCHING: 'إفاد آلى',
            MANUAL_PARAGRAPH: 'إفاد اليدوى: يسمح للسيارات القريبة بإستلام طلبات الالتقاط الفورية',
            AUTOMATIC_PARAGRAPH: 'إفاد الآلى :تخصيص السيارة الاقرب لطلب الالتقاط الفورى',
            MANUAL_DISTRIBUTION: 'توزيع يدوى',
            AUTOMATIC_DISTRIBUTION: 'توزيع آلى',
            CONFIGURATION_ITEM: 'بند الإعدادت',
            VALUE: 'القيمة',
            UNIT: 'الوحدة',
            DESCRIPTION: 'الوصف',
            SELECT_COUNTRY: 'اختر دولة',
            SELECT_CITY: 'اختر مدينة',
            STREET_NAME: 'اسم الشارع ',
            STREET: 'الشارع',
            BUILDING_NUMBER: 'رقم المبنى',
            WASEL_CODE: 'واصل كود',
            LATITUDE: 'خط العرض',
            LONGITUDE: 'خط الطول',
            EDIT_BUILDING: 'تعديل المبنى',
            AREA: 'المنطقة',
            DELETE_BUILDING: 'حذف المبنى',
            DELETE_CONFIRMATION: 'تأكيد عملية الحذف',
            DELETE: 'احذف',
            EDIT: 'تعديل',
            RESCHEDULE: 'إعادة جدوله',
            DELETE_USER: 'حذف عميل',
            EDIT_USER: 'تعديل بيانات العميل',
            IMAGE: 'الصورة الشخصية',
            LICENSE_TYPE: 'نوع الرخصة',
            LICENSE_ID: 'رقم الرخصة',
            LICENSE_EXPIRY_DATE: 'تاريخ انتهاء الرخصة',
            SELECT_VEHICLE_PURPOSE: 'اختار الغرض من الشاحنة',
            SELECT_VEHICLE_TYPE: 'اختار نوع الشاحنه',
            MODEL: 'الطراز',
            MOTOR_NO: 'رقم الموتور',
            COLOR: 'اللون',
            WEIGHT_KG: 'الوزن(كج)',
            WIDTH: 'العرض',
            HEIGHT: 'الارتفاع',
            LENGTH: 'الطول',
            SELECT_BUILDING: 'اختر المبنى',
            SELECT_BUILDING_TYPE: 'اختر نوع المبنى',
            CAPACITY: 'بيانات الحمولة',
            EDIT_VEHICLE: 'تعديل بيانات الشاحنة',
            ITEMS_PER_PAGE: 'عدد العناصر فى الصفحة',
            DELETE_SCHEDULED_REQUEST: 'حذف طلب من الجدول',
            PACKAGE_IMGS_HINT: 'صورة الشحنه  (أضف صوره واحدة على الأقل)',
            PACKAGE_LABELING: 'تمييز الشحنه',
            EDIT_PACKAGE: 'تعديل بيانات الشحنه',
            SELECT_PACKAGE_TYPE: 'أختر نوع الشحنه',
            SELECT_SHIPMENT_SERVICE: 'اختار خدمة الشحن',
            SELECT_SUB_SHIPMENT_SERVICE: 'اختار خدمة شحن فرعية',
            DELETE_PACKAGE: 'حذف الشحنه',
            LEFT: 'right',
            RIGHT: 'left',
            OF: 'من',
            IMAGE_REQUIRED: 'الصورة مطلوبة',
            REQUIRED: ' مطلوب',
            INVALID: 'غير صحيح',
            SHORT: 'قصير',
            LONG: 'طويل',
            ENTER_NUM_ONLY: 'ادخل ارقام فقط',
            NUMBER: 'الرقم',
            MAX_CHARACTERS: 'يجب ان لا يتعدى {{number}} حرف',
            MIN_CHARACTERS: 'يجب ان يكون{{number}} حرف',
            MAX_NUMBERS: 'يجب ان لا يتعدى {{number}} رقم',
            MIN_NUMBERS: 'يجب ان يكون{{number}} رقم',
            FORMAT_error: ' استخدم الحروف(ا-ى)و الارقام و المسافة فقط',
            ADD_USER_SUCCESS_MSG: 'تم إضافة العميل بنجاح',
            DEL_USER_SUCCESS_MSG: 'تم حذف العميل بنجاح',
            EDIT_USR_SUCCESS_MSG: 'تم تعديل العميل بنجاح',
            ADD_BUILD_SUCC_MSG: 'تم إضافة المبنى بنجاح',
            DEL_BUILD_SUCC_MSG: 'تم تغيير حالة المبنى بنجاح',
            DEL_BUILD_ERR_MSG: 'توجد مشكلة في تغيير حالة المبنى',
            EDIT_BUILD_SUCC_MSG: 'تم تعديل المبنى بنجاح',
            ERROR_BUILD: 'المبنى محذوف بالفعل',
            ERROR_BUILDS: 'المبنى/المبنانى محذوف بالفعل',
            ERROR_BUILDS_WITH_VEH: 'بعض المركبات او الاعضاء مسندة بالمباني المختارة',
            GENERAL_DEL_ERROR: 'بعض العناصر محذوفه بالفعل',
            NO_INTERNET: 'لقد حدث حطأ غير متوقع قد يكون بسبب الشبكه. برجاء التأكد من الشبكه او الاتصال بالادمن',
            ERROR_USER: 'العميل محذوف بالفعل',
            ERROR_USERS: 'العميل/ العملاء محذوف بالفعل',
            ADD_PACKAGE_SUCC_MSG: 'تم إضافة الشحنه بنجاح',
            DEL_PACKAGE_SUCC_MSG: 'تم حذف الشحنه بنجاح',
            EDIT_PACKAGE_SUCC_MSG: 'تم تعديل الشحنه بنجاح',
            ERROR_PACKAGE: 'الشحنه محذوفة بالفعل',
            ERROR_PACKAGES: 'الشحنه / الشحنات محذوفه بالفعل',
            DEL_REQ_SUCC_MSG: 'تم حذف الطلب بنجاح',
            FAIL_PACKAGE: 'فشل فى تحميل بيانات الشحنه',
            FAIL_REQ: 'فشل فى تحميل بيانات الطلب',
            EDIT_PICKUP_SUCC_MSG: 'طلب الالتقاط تم تعديله بنجاح',
            ADD_VHCL_SUCC_MSG: 'تم إضافه الشاحنه بنجاح',
            DEL_VHCL_SUCC_MSG: 'تم حذف الشاحنة بنجاح',
            EDIT_VHCL_SUCC_MSG: 'تم تعديل الشاحنة بنجاح',
            ERROR_VHCL: 'الشاحنه محذوفة بالفعل',
            ERROR_VHCLS: 'الشاحنه/الشاحنات محذوفه بالفعل',
            FAIL_USER: 'فشل فى تحميل بيانات العميل',
            AWESOME: 'رائع',
            WARNING: 'تحذير...',
            OH_NO: 'يا إلهى!',
            MAX_DIMEN: 'الابعاد القصوى:-',
            MAX_WEIGHT: 'اقصى وزن:-',
            AT_LEAST_ONE_IMG: 'على الأقل صورة واحده',
            INVALID_NUMBER: 'رقم غير صحيح',
            BIG_NUMBER: 'رقم كبير',
            BIGGER_THAN_STANDARD: 'اكبر من المواصفات القياسية',
            LESS_THAN_STANDARD: 'اقل من المواصفات القياسية',
            INVALID_ID: 'رقم غير صحيح',
            TO_REQUEST_DATE: 'تاريخ الطلب الى',
            TO_PICKUP_DATE: 'تاريخ الالتقاط الى',
            ADD_IMAGE: 'أضف الصورة',
            REMOVE_IMAGE: 'احذف الصوره',
            PACKAGE_IMG: 'صورة الشحنه',
            PACKAGE_DEF_IMG: 'صورة الشحنه الافتراضيه',
            USER_IMG: 'صورة العميل',
            USER_DEF_IMG: 'صورة العميل الافتراضيه',
            PACKAGE_FIRST_IMG: 'صورة الشحنه الاولى',
            PACKAGE_2nd_IMG: 'صورة الشحنه الثانيه',
            IMG_TOO_LARGE: 'حجم الصوره كبير',
            FILE_NOT_IMG: 'الملف ليس بصورة',
            FILE_NOT_SUPP: 'الملف غير مدعوم',
            FILE_IS_DUPLICATED: 'الملف مكرر',
            FILE_CORRUPTED: 'الملف تالف',
            IMAGE_UPLOAD_ERR: 'لم يتم رفع الصور',
            DATE_FORMAT: 'yyyy/MM/dd',
            KG: 'كج',
            PM: 'م',
            AM: 'ص',
            MM: 'دد',
            HH: 'سس',
            SAVE: 'حفظ',
            REMOVE: 'حذف',
            ADD_ROLE: 'أضف وظيفه',
            ROLE_NAME: 'إسم الوظيفه',
            ROLE_DES: 'وصف الوظيفه',
            ACTIVATION: 'التفعيل',
            MODULE_NAME: 'اسم الوحده',
            SET_PERMISSIONS: 'أدخل الصلاحيات',
            PERMISSIONS: 'الصلاحيات',
            VIEW: ' معاينة',
            EDIT_ADD: 'تعديل/إضافه',
            ACTIVE_DEACTIVATE: 'تفعيل',
            ASSIGN_USER: 'أضف عميل',
            CANCLE: 'إلغاء',
            SERCH_USER: 'ابحث عن عميل',
            NO_USER_ASSIGNED: 'لم يتم إسناد عميل',
            TOTAL_PICKUPS: 'مجموع الالتقاطات',
            TOTAL_DELIVERIES: 'مجموع التوصيلات',
            EDIT_ROLE: 'تعديل الوظيفه',
            IMG_CNOT_UPLOD: "لا يمكن تحميل الصور(ه)",
            DEVICES: 'الأجهزه',
            ADD_DEVICE: 'أضف جهاز',
            DEL_DEVICE_SUCC_MSG: 'تم تغيير حالة الجهاز بنجاح',
            DEL_DEVICE_ERR_MSG: 'خطأ في تغيير حالة الجهاز',
            PHONE_NUMBER: 'رقم التليفون',
            PRIVILEGE_ERROR: 'حدث خطأ ما .. اعد المحاولة لاحقاً',
            DEACTIVATE_SELECTED: 'عطل الاختيار',
            IMEI: 'رقم التعريف الدولى للجهاز',
            EDIT_DEVICE: 'عدل بيانات الجهاز',
            DRIVER_NAME: 'اسم السائق',
            DRIVER_NUMBER: 'رقم السائق',
            JOB_ID: 'رقم الطلب',
            CUSTOMER_NAME: 'اسم الزبون',
            CUSTOMER_NUMBER: 'رقم الزبون',
            JOB_STATUS: 'حاله الطلب',
            PICKUP_MAP_SUMMARY: '{{number}} من مجموع {{total}} طلب التقط',
            DILEVERY_MAP_SUMMARY: '{{number}} من مجموع {{total}} طلب ارسل',
            ACTIVE_VEHICLE: 'السيارات الفعاله',
            ADD_ACTIVE_VEHICLE: 'أضف سياره فعاله',
            DEVICE_ID: 'رقم الجهاز',
            ADD_DEVICE_SUCC_MSG: 'تم إضافة الجهاز بنجاح',
            EDIT_DEVICE_SUCC_MSG: 'تم تعديل الجهاز بنجاح',
            SELECT_BRAND: 'اختر ماركه',
            REMOVE_ASS_BTN: 'ازالة المستخدمين المخصصين',
            RETURN_HOME: 'عوده للصفحه الرئيسيه',
            ERROR_401: 'غير مصرح لك الدخول لهذه الصفحه',
            ERROR_404: 'انت ضائع',
            ERROR_404_msg: 'لا نستطيع إيجاد الصفحه المطلوبه',
            ERROR_500: 'نأسف ! خطأ من الخادم',
            ERROR_500_msg: 'حدث خطأ ما , أعد المحاوله بعد لحظات',
            CHASSIS: 'رقم الشاسيه',
            MULTISTOP: 'وقوف متكرر',
            PICKUP: 'الالتقاط',
            PICKUP_DELIVERY: 'الالنقاط و التوصيل',
            PASSWORD: 'كلمة المرور',
            DELETE_ACTIVE_VEHICLE: 'ازالة الشاحنات المفعلة',
            SELECT_VEHICLE: 'اختار رقم الشاحنه',
            SELECT_DRIVER: 'اختار اسم السائق',
            SELECT_DEVICE: 'اختار رقم الجهاز',
            SELECT_WORKSHIFT: 'اختار المواعيد',
            SELECT_CALENDER: 'اختار التقويم',
            SELECT_RETURN_ADDRESS: 'اختار عنوان الأسترجاع',
            VEHICLE: 'الشاحنة',
            DEVICE: 'الجهاز',
            DRIVER: 'سائق',
            CALENDER: 'التقويم',
            WORKSHIFT: 'مواعيد العمل',
            DEL_ACTIVE_VEHICLE_SUCC_MSG: 'تم ازالة الشاحنة المفعلة بنجاح',
            SIZE: 'الحجم',
            CORRESPONDENCE: 'الوزن الموافق بالكيلو',
            ADD_PACKAGE_WEIGHT: 'إضافه وزن شحنه',
            ADD_PW_SUCC_MSG: 'تم اضافه وزن الشحنه بنجاح',
            NEW: 'جديد',
            SCHEDULED_FOR_PICKUP: 'مجدول للألتقاط',
            AWAITING_PICKUP: 'فى إنتظار الالتقاط',
            WAITING_FOR_CUSTOMER_ALTERNATIVE: 'فى انتظار العميل',
            ACTION_NEEDED: 'إتخذ إجراء',
            IN_PICKUP_VERIFICATION: 'التحقق من الإلتقاط',
            IN_DELIVERY_VERIFICATION: 'التحقق من التوصيل',
            PICKEDUP: 'تم الإلتقاط',
            CANCELED: 'ألغيت',
            AVAILABLE_ACTIVE_VEHICLES: 'السيارات الفعاله المتاحه',
            SCHEDULED_JOB_ORDERS: "الطلبات المجدوله",
            JOB_ORDERS_DISTRIBUTION: "توزيع الطلبات",
            CLEAR_ALL: "محو كلى",
            VERIFY: "التحقق",
            ASSIGN: 'اسناد',
            POINTERROR_A: 'مكان المبنى غير معرف',
            POINTERROR_B: 'المبنى يقع في منطقة مباني اخرى',
            POINTERROR_C: 'موقع المبنى خارج نطاق التغطية',
            POLYGONERROR_A: 'ارسم حدود المنطقة',
            POLYGONERROR_B: 'حدود المنظقة متقاطع مع الابنية الاخرى',
            DRAWPOLYGON: 'ارسم منطقة التغطية',
            ADDMARKER: 'اضف علامة',
            REM_POL_MAR: 'ازالة منطقة التغطية',
            CHK_PNT_MTCH: 'فحص نقطة المبنى',
            CHK_PLGN_MTCH: 'فحص منطقة التغطية',
            ROLE_S: 'الوظائف',
            SOME_REQ_EXIST: 'توجد طلبات متعلقة بهذه المركبة',
            DEACTIVE_CONFIRMATION: 'هل تريد الغاء تعفيل المركبة',
            DEACTIVATE_VHCL_SUCC_MSG: 'تم الغاء تفعيل المركبة بنجاح',
            DEACIVATE_ACTIVE_VEHICLE: 'الغاء تفعيل مركبة',
            ASSIGN_ORDER: 'توجيه طلب',
            CALENDAR: 'التقويم',
            CALENDAR_CONFIG: 'ضبط التقويم',
            JOB_DISTRIBUTION: 'توزيع الاعمال',
            DEVICE_MODEL: 'طراز الجهاز',
            SLCT_DEVICE_MODEL: 'اختار طراز الجهاز',
            CANCEL_ONDEMAND_SUCC_MSG: 'تم إالغاء الطلب بنجاح',
            SCHEDULE_REQUEST: 'جدول الطلب',
            SCHEDUL_ONDEMAND_SUCC_MSG: 'تم جدولة الطلب بنجاح',
            CONFIRM_CANCELLATION: 'تأكيد الإلغاء',
            CONFIRM_MSG_CANCELLATION: 'هل انت متأكد من إلغاء الطلب؟',
            SELECT_CANCELLATION_REASON: 'اختر سبب الالغاء',
            ADDITIONAL_NOTES: 'ملاحظات إضافيه',
            CONFIRM: 'تأكيد',
            SCHEDULE: 'جدول',
            SEND_NOTIFICATION: 'قم بإرسال إشعار',
            CANCEL_REQUEST: 'إلغاء الطلب',
            SEND_NOTIFICATION_SUCC_MSG: 'تم إرسال الإشعار بنجاح',
            CANCELLATION_REASON: 'سبب الإلغاء',
            ADD_ACTIVE_VEH: 'اضف مركبة فعالة',
            ERROR_DRIVER_WITH_VEH: 'السائق مستخدم في السيارات الفعالة',
            ERROR_VEH_WITH_VEH: 'السيارة مستخدمة في السيارات الفعالة',
            ERROR_DIVICE_WITH_VEH: 'الجهاز مستخدم في السيارات الفعالة',
            SET_WORKING_DAYS: 'قم بتعيين ايام العمل',
            SET_WORKING_SHIFTS: 'قم بتعيين ساعات العمل',
            SET_SEL_DAY_W_N: 'حدد اذا كان اليوم عطله ام عمل',
            SET_WORK: 'تعيين الايام الى ايام عمل',
            SET_NON_WORK: 'تعيين الايام الى ايام عطلة',
            ADD_MORE: 'اضف المزيد',
            SHIFT_OCCURS: 'المدة تقع في مدة اخرى',
            ENTER_DATE: 'مدة العمل غير صحيح',
            SHIFT_LESS: 'الى الفترة افل او يساوي من',
            SATURDAY: 'السبت',
            SUNDAY: 'الاحد',
            MONDAY: 'الاثنين',
            TUESDAY: 'الثلاثاء',
            WEDNESDAY: 'الاربعاء',
            THURSDAY: 'الخميس',
            FRIDAY: 'الجمعة',
            DEF_UP_6: 'اضف بحد اقصى 6 من المدة',
            WORKING_DAYS: "ايام عمل",
            NON_WORKING_DAYS: "ايام عطله",
            ADD_SHIFT: "اضف اوقات عمل",
            APPLY_CONFIRMATION: 'توقيت العمل سوف يؤثر على المركبات المفعلة هل تريد الاستمرار؟',
            CHANGE_SHIFT: 'تغيير توقيت العمل',
            REMAINING_ORDERS: "الطلبان المتبقيه",
            ETA: "الوقت المتوقع للوصول",
            PICKUP_REQUESTS: "طلبات الالتقاط",
            ON_DEMAND_PICKUPS: "طلبات فورية",
            SCHEDULE_PICKUPS: "طلبات مجدولة",
            DISPATCH_ACTIVITIES: "انشطة الارسال",
            ACTIVE_JOBS: "اعمال مفعلة",
            VEHICLE_MAP_VIEW: 'خريطة المركبات',
            BUILDINGS_MAP_VIEW: 'خريطة المباني',
            SYSTEM_FEATURES: 'مميزات النظام',
            USERS_MANAGEMENT: 'ادارة الاعضاء',
            ROLES_PERMISSIONS: 'قائمة الوظائف',
            WORK_CALENDAR: 'ايام العمل',
            USER_TYPE: 'نوع العميل',
            SUCC_ADD_ROLE: 'تم إضافة الوظيفه بنجاح',
            DRIVER_RESPONSE: "رد السائق",
            ACCEPTED: "مقبول",
            REJECTED: "مرفوض",
            ACCEPT: "مقبول",
            REJECT: "مرفوض",
            REASSIGN: "إعاده اسناد",
            REASSIGN_ALL: "إعاده اسناد الكل",
            NO_ASSGINED_ORDERS_OV: "لا يوجد اى اعمال مسنوده",
            LOADING_ACTVITIES: 'الانشطة المحملة',
            ADMINSTRATE: 'ادارة',
            SET_ROLE: 'أعد وظيفه',
            SET_ROLES: 'أعد وظائف',
            MINS: " دقيقه",
            ACTIVE_VEHICLE_ID: 'رقم السيارة الفعاله',
            BOX: 'صندوق',
            DOCUMENT: 'مستند',
            RECEIVED_FROM_HH_MM: ' أرسلت  من  (س :د)  ',
            DRIVER_RATING: 'تقييم السائق',
            DRIVERS_RATING: 'تقييم السائقين',
            ADD_ROLE_HINT: 'أختار الوظايف ليتم اسنادها للعملاء المختارين',
            SELECT_ROLE: 'أختر وظيفه',
            SCHEDULE_REQUEST_CAP: 'جدول الطلب',
            BACK_OFFICE_EMPLOYEE: 'موظف مكتبى',
            BACK_OFFICE: 'موظف مكتبى',
            DUPLICATED_USER_MSG: 'العضو موجود بالفعل',
            EDIT_ROLE_MSG_SUCC: 'تم تعديل الوظيفه بنجاح',
            ADD_ROLE_SUCC_MSG: 'تم إضافة الوظيفه بنجاح',
            HELLO: 'مرحبا ',
            THIS_DASHBOARD: 'هذه صفحتك الرئيسيه',
            REASON_ONE: 'السبب الأول',
            REASON_TWO: 'السبب الثانى',
            REASON_THREE: 'السبب الثالث',
            SUCCESS: "نجاح",
            IN_GRACE_PERIOD: "فى فتره السماح",
            FAIL: "فشل",
            STARTS_AT: "تبداء من",
            CASH: 'كاش',
            CANCEL_ONDEMAND_ERR_MSG: 'هذا الطلب تم الغاءه سابقا',
            USER_CANCEL: 'الغاء من المستخدم',
            ERR_ASSIGN_DRI: 'خطأ في تعيين صلاحيات للسائق',
            ACTIVE_ORDERS: 'الطلبات الفعاله',
            VEH_ASSIGN_SUCC_MSG: 'تم تعيين المركبة بنجاح',
            DELIVERY_REQUESTS: 'طلبات التوصيل',
            REQUESTS: 'الطلبات',
            DELIVERY_SCHEDULED_FOR: 'التوصيل المجدول فى ',
            DELIVERY_DATE: 'تاريخ التوصيل',
            DELIVERY_TIME: 'وقت التوصيل',
            CREDIT_CARD: 'بطاقة الإئتمان',
            PACKAGE_VERIFICATION: 'التحقق من بيانات الشحنه',
            VERIFICATION_BY_DRIVER: 'التحقق من السائق',
            ASSIGNED: 'تم الإسناد',
            VEHICLE_OVERWEIGHT: 'وزن زائد',
            PLAN_SUBMIT_SUCC: 'تم تطبيق الخطه بنجاح',
            TRACKING_NUMBER: 'رقم المتابعه',
            PACKAGE_STATUS: 'حاله الشحنه',
            SCHEDULED_FOR_DELIVERY: 'مجدوله للتوصيل',
            DELIVERED: 'تم التوصيل',
            RESCHEDULE_FOR_RETURN: 'إعاده جدوله للإسترجاع',
            RESCHEDULED_FOR_RETURN: 'إعاده جدوله للإسترجاع',
            RE_SCHEDULED_FOR_PICKUP: 'إعاده جدوله للألتقاط',
            RESCHEDULED_FOR_DELIVERY: 'اعادة جدولة للتوصيل',
            RESCHEDULED: 'تم إعادة الجدوله',
            DELIVERY_REQUEST_DETAILS: 'تفاصيل طلبات التوصيل',
            EDIT_DELIVERY_SUCC_MSG: 'تم إعادة  جدولة طلب التوصيل بنجاح',
            VEHICLE_STATE: 'حالة الشاحنه',
            STARTS_FROM: 'نقطة البداية',
            DESTINATION: 'الوجهه',
            PICKUPS_STATUS: 'حالة طلبات الالتقاط',
            DELIVERY_STATUS: 'حالة طلبات التوصيل',
            ACTIVE_ORDER: 'الطلب الفعال',
            VEHICLE_BRAND: 'ماركة الشاحنه',
            VEHICLE_COLOR: 'لون الشاحنه',
            VEHICLE_MODEL: 'طراز الشاحنه',
            ORDERS_IN_QUEUE: 'جدول الطلبات',
            ARRIVAL_TIME_INTERVAL: 'وقت الوصول المتوقع',
            OUT_FOR_DELIVERY: 'فى الطريق للتوصيل',
            RETURNED: 'أرجعت',
            CANCELLED: 'ألغيت',
            VEH_RELATED: 'المركبة مخصصة لخطة عمل',
            OUT_OF: 'من',
            SCHEDULED_FOR_RETURN: 'موجدول للإسترجاع',
            RETURN_ADDRESS: 'عنوان الاسترجاع',
            SENDER_ADDRESS: 'عنوان الراسل',
            SENDER_MOBILE: 'تليفون الراسل',
            RETURN_DATE: 'تاريخ الاسترجاع',
            DEVICE_NUMBER: 'رقم الجهاز',
            CITY: 'المدينة',
            DIFFRENT_ADDRESS: 'عنوان آخر',
            RETURN_LOCATION: 'عنوان العائد عليه',
            RESCHEDULE_FOR_RETURN_SUCCESS: 'تم إعاده الاسترجاع بنجاح',
            EXISTING_PLAN: 'هناك خطه أخرى مفعله',
            RETURN_REQUESTS: 'طلبات الاسترجاع',
            PLAN_DETAILS: 'تفاصيل الخطه',
            REPLAN: 'إعاده تخطيط',
            CREATED_AT: 'تاريخ الإنشاء',
            SUBMITTED_AT: 'تاريخ العرض',
            FAQ: 'التعليمات',
            ADD_FAQ: 'اضف تعليمات',
            EDIT_FAQ: 'تعديل التعليمات',
            LANGUAGE: 'لغه',
            SELECT_LANGUAGE: 'إختار اللغه',
            ARABIC: 'العربيه',
            ENGLISH: 'الإنجليزيه',
            QUESTION: 'السؤال',
            ANSWER: 'الجواب',
            RETURN_REQUEST_DETAILS: 'تفاصيل طلبات الاسترجاع',
            ADD_FAQ_SUCCESS_MSG: 'تم إضافه التعليمات بنجاح ',
            FREQ_ASK_QUES: 'الاسأله المطروحه عادتا',
            N_A: 'غير متاح',
            ACTIVE_ORDER_IN_PROGRESS: 'الطلبات الفعاله على قيد التنفيذ',
            ASSI_DRIV_VEH_DET: 'تفاصيل السائق و السياره',
            CANT_LOAD_MAP: 'عدم الامكانيه من تحميل الخريطه حاليا',
            IN_RETURN_VERIFICATION: 'التحقق من الرجوع',
            DELETE_FAQ: 'ازالة التعليمات',
            "ON-DEMAND": 'فوري',
            FRENCH: 'الفرنسية',
            CONFIRM_PASSWORD: 'تأكيد كلمه السر',
            PASSWORD_CHANGED_SUCCESS: "تم تغيير كلمه المرور بنجاح",
            EMAIL_SUCCESS_SENT: "تم ارسال البريد الالكترونى بنجاح",
            DOMESTIC: "داخلى",
            NEXTDAY: "اليوم التالى",
            SCHEDULED: "مجدول",
            CHANGE_PASSWORD: "تغيير كلمه المرور",
            NEW_PASSWORD: "كلمه المرور الجديده",
            OLD_PASSWORD: "كلمه المرور القديمه",
            PASSWORDS_DONT_MATCH: "كلمات المرور غير متطابقين",
            EDIT_PROFILE: "تعديل البيانات",
            TO_DELIVERY_DATE: "تاريخ التوصيل",
            RECIP_ADDRESS: 'عنوان المستلم',
            USER_CANCELED: 'المستخدم الغى',
            ON_DEMAND_DETAILS: 'تفاصيل الطب الفوري',
            SCHEDULED_DETAILS: 'تفاصيل الطلب المجدول',
            CREATED_BY: "المنشئ",
            CREATED_FROM: "تاريخ الأنشاء",
            DRIVER_RESPONSE_TIME: 'سرعه رد السائق',
            DISPATCH_MODE: 'وضع الارسال',
            NEARBY_VEHICLES_RANGE: 'السيارات القريبه',
            TRIALS_OF_LOOKING_FOR_VEHICLE: 'محاولات البحث عن السياره',
            TRIALS_INTERVAL_OF_LOOKING_FOR_VEHICLE: 'الفاصل الزمنى فى محاولات البحث عن السياره',
            WAITING_TIM_F_STTS_LKN_F_VEH: 'waiting time for status of looking for vehicle',
            TRIALS_INTRV_F_STTS_LKN_F_VEH: 'trials interval for status of looking for nearby vehicle',
            EMERGENCY_CAPACITY: 'سعة الطوارئ',
            DISTRIBUTION_MODE: 'وضع التوزيع',
            AUTOMATIC_PLAN_CREATION_TIME: 'وقط انشاء الخطه الاوتوماتيكيه',
            COUNT_DOWN: 'عد تنازلى',
            LATE_TIME_INTERVAL: 'الفاصل الزمني المتأخر',
            EARLY_TIME_INTERVAL: 'الفاصل الزمنى المبكر',
            START_TIME_INCREMENT_FACTOR: 'بدء عامل زيادة الوقت',
            REQUEST_PROCCESSING_TIME: 'وقط تنفيذ الطلب',
            GRACE_PERIOD_TIME: 'فتره السماح',
            C_COUNT_DOWN_DESC: 'عد تنازلى للردار',
            C_DRIVR_RESPNS_TIME_DESC: 'the maximum time given to the driver to grab any on-demand pickup request.The maximum time given to the driver to grab any on-demand pickup request.The maximum time given to the driver to grab any on-demand pickup request.The maximum time given to th',
            C_NEAR_VEH_RANG_DESC: 'a diameter from the pickup-location upon which a vehicle can be defined as nearby',
            C_TRAILS_LKN_F_VEH_DESC: 'number of trails the system conduct to look for vehicle for on-demand pickup request',
            C_TRLS_INTRV_F_LKN_VEH_DESC: 'time interval between trails the system conduct to look for vehicle for on-demand pickup request',
            C_WTNG_TIM_F_STTS_LKN_F_VEH_DESC: 'the time the system will keep looking for vehicle',
            C_TRLS_INTRV_F_STTS_LKN_F_VEH_DESC: 'time interval between trails the system conduct to look for nearby vehicle',
            C_EMRGNCY_CAP_DESC: 'the percent of minimum availabe capacity in vehicle',
            C_ATMTC_PLN_CRTION_TIM_DEC: 'time of creating automatic distribution plan',
            C_LATE_TIME_INTERVAL_DESC: 'الفاصل الزمني المتأخر',
            C_EARLY_TIME_INTERVAL_DESC: 'الفاصل الزمنى المبكر',
            C_START_TIME_INCREMENT_FACTOR_DESC: 'بدء عامل زيادة الوقت',
            C_REQUEST_PROCCESSING_TIME_DESC: 'وقط تنفيذ الطلب',
            C_GRACE_PERIOD_TIME_DESC: 'فتره السماح',
            BASIC_INFO: 'معلومات أساسية',
            CANCEL: 'إلغاء',
            CHANGE: 'تغير',
            CHANGE_EMAIL: 'غير البريد الالكترونى',
            CHANGE_EMAIL_SUCCESS: 'تم تغيير البريد الالكترونى بنجاح',
            ACCOUNT_DETAILS: 'تفاصيل الحساب',
            SENDER_PHONE: 'هاتف المرسل',
            RECIPIENT_PHONE: 'هاتف المستقبل',
            OUT_FOR_RETURN: 'في الطريق للاسترجاع',
            KM: 'كم',
            SECOND: 'ثانيا',
            HRS: 'ساعات',
            TRIALS: 'محاولات',
            PERCENT: 'نسبه مئويه',
            ON_DEMAND_SERVICES: 'الخدمات الفوريه',
            SCHEDULED_SERVICES: 'الخدمات المجدوله',
            TRANSIT_SERVICES: 'خدمات الترانزيت',
            CHECK_YOUR_PASSWORD: 'من فضلك افحص كلمة السر',
            PROGRESS: 'تقدم',
            AVAILABLE: 'متاح',
            NEW_RETURN: 'استرجاع جديد',
            CANCELED_DELIVERY: 'توصيل ملغى',
            ON_ROUTE: 'في الطريق',
            ON_BREAK: 'في عطلة',
            BUSY: 'مشغول',
            NO_VEHICLES: 'لا يوجد مركبات',
            NO_COVERAGE: 'غارج من نطاق الخدمه',
            NOCOVERAGE: 'غارج من نطاق الخدمه',
            NO_CAPACITY: 'لا يوجد مساحة تخزينية',
            NOCAPACITY: 'لا يوجد مساحة تخزينية',
            COUNTRY_CODE: 'كود الدوله',
            SELECT_COUNTRY_CODE: 'اختر كود الدوله',
            ADVANCED_SEARCH: 'البحث المتقدم',
            APPLY: 'تطبيق',
            DELETE_RETURN_REQUEST: 'حذف طلب الاسترجاع',
            HUB_ADMIN: 'مدير مبنى',
            CORPORATE_DRIVER: 'سائق الشركة',
            HUB_NAME: 'اسم المبنى',
            FREELANCER_ADMIN: 'مدير موقع حر',
            SUPERVISOR: 'مشرف',
            OPERATION_BACKOFFICE: 'موظف اعمال مكتبة',
            OFFLOADING: 'التفريغ',
            TOTAL_PACKAGES: 'إجمالى الشحنات',
            FREELANCER_REQUESTS: 'طلبات السائقين',
            LAUNCH_CITY: 'مدينة القيادة',
            VEHICLE_STATUS: 'حالة السيارة',
            FREELANCER_DETAILS: 'تفاصيل السائق',
            CITY_TO_DRIVE_IN: 'مدينة القيادة',
            DRIVERS_LICENSE: 'رخصة القيادة',
            DRIVER_ID: 'رخصة السائق',
            YEAR: 'عام',
            PLATE_NUMBER: 'رقم لوحة',
            TYPE: 'نوع',
            MOTOR_NUMBER: 'رقم المحرك',
            WEIGHT: 'وزن',
            CHASSIS_NUMBER: 'رقم الشاسيه',
            VEHICLE_OWNERSHIP_ID: 'رقم ملكيه السياره',
            CRIMINAL_RECORDS: 'سجل إجرامى',
            BIRTH_CERTIFICATE: 'شهاده ميلاد',
            REPORT_MISSING_DOCUMENTS: 'إبلاغ عن مستندات غائبه',
            DOCUMENTS: 'مستندات',
            ALL_BUILDINGS: 'كل المبانى',
            OPERATIONS_RANKS: 'ترتيب العمليات',
            CUSTOMERS_AGE: 'عمر الزبائن',
            SUCCEEDED: 'تم بنجاح',
            MODERATE: 'معتدل',
            LOW: 'منخفض',
            EXTREMELY_BUSY: 'مشغول جدا',
            CORPORATE: 'موظف',
            ALL: 'الكل',
            ONESTARS: '1 نجم',
            TWOSTARS: '2 نجوم',
            THREESTARS: '3 نجوم',
            FOURSTARS: '4 نجوم',
            FIVESTARS: '5 نجوم',
            GO_EXTRA: 'العمل الإضافى',
            SEVEN_DAYS: 'آخر 7 أيام',
            THIRTY_DAYS: 'آخر 30 يوما',
            PACKGESLESSTHAN5KG: 'اقل من ٥ كج',
            PACKGESLESSTHAN10KG: 'أقل من ١٠ كج',
            PACKGESLESSTHAN25KG: 'أقل من ٢٥ كج',
            FREELANCERDRIVER: 'السائق الحر',
            AGEBETWEEN21AND30: 'سن من ٢١ حتى ٣٠',
            LESSTHAN21: 'سن اقل من ٢١',
            AGEBETWEEN31AND45: 'سن من ٣١ حتى ٤٥',
            AGE_ABOVE_45: 'سن اكبر من ٤٥',
            OTHERAGES: 'الآخرين',
            OTHERS: 'الآخرين',
            MINUTES: 'دقائق',
            AVG_TIME_AT_CUSTOMER_PICK: 'معدل الوقط عند الزبون عند الالتقاط',
            MISSING_DOCUMENTS_REPORTED: 'تم البلاغ عن المستنادات الناقصة',
            FREELANCER_REJECTED: 'تم رفض العامل الحر', //
            FREELANCER_ACCEPTED: 'تم قبول العامل الحر', //
            ACCEPT_PACKAGE_OFFLOADING: 'هل انت متاكد انك تريد القبول', //
            REPORT_PACKAGE_OFFLOADING: 'هل انت متاكد انك تريد الابلاغ', //
            UNDO_PACKAGE_OFFLOADING: 'هل انت متاكد انك تريد العودة', //
            PACKAGE_CATEGORY: 'فئة الطرد',
            RECEIVE: 'استلام',
            REPORT_MISSING: 'ابلاغ مفقود',
            VEH_STATUS_CHAN_SUCC: 'حالة المركبة تغيرت بنجاح',
            EMP_STATUS_CHAN_SUCC: 'حالة المستخدم تغيرت بنجاح',
            VEH_STATUS_NOT_CHAN_SUCC: 'خطأ في تغيير حالة المركبة',
            AMOUNT: 'كمية',
            IN_TODAYS_PLAN: 'فى خطه اليوم',
            OFFLOADING_ACTIVITIES: 'عمليات التفريغ',
            CONFIGURATION: 'الاعدادات',
            BUILDING_CONFIG: 'اعدادات المبنى',
            MOBILE_CONFIG: 'اعدادات الهاتف',
            ON_DEMAND_CONFIG: 'إعدادات الطلبات الفوريه',
            DISTRIBUTION_CONFIG: 'إعدادات التوزيع',
            GENERAL_OPERATIONS: 'إعدادات عامه',
            CONTACT_US: 'اتصل بنا',
            HOTLINE_TITLE: 'عنوان الخط الساخن',
            HOTLINE_NUMBER: 'رقم الخط الساخن',
            CONTACT_US_FOR_CUS_APP: 'اتصل بنا فى برنامج العميل',
            EMAIL_ADD_TITLE: 'عنوان البريد الالكترونى',
            DAILY_WORKING_HOURS: 'ساعات أيام العمل',
            VACATION_WORKING_HOURS: 'ساعات أيام الأجازات ',
            DAILY: 'يوميا',
            CONTACTUS_SAVED_SUCCESS: 'تم الحفظ على الاتصال بنا بنجاح',
            IN_DISTRIBUTION: 'فى التوزيع',
            PENDING: 'في الانتظار',
            BACK_CUSTOMER_LIST: 'العودة إلى قائمة العملاء',
            STATISTICS: 'الإحصاء',
            CUSTOMER_REQUESTS: 'طلبات العميل',
            PROCESSED: 'تم بنجاح',
            CUSTOMER_USED_CATEGORY: 'الفئة الأكثر استخداما',
            ARCHIVED_DELIVERY: 'أرشيف التسليم',
            ARCHIVED_RETURNS: 'أرشيف الاسترجاع ',
            RANKING: 'ترتيب',
            TOTAL_OPERATIONS: 'اجمالى عدد العمليات',
            IN_PROGRESS: 'قيد الانتظار',
            NO_CATEGORIES: 'لا يوجد اقسام',
            PICKUP_HISTORY: 'تاريخ الالتقاط',
            DELIVERY_HISTORY: 'تاريخ التسليم',
            RETURN_HISTORY: 'تاريخ الاسترجاع',
            REQUEST_TIME: 'وقت الطلب',
            PICKUP_TIME: 'معاد الاختار',
            IMAGES: 'صور',
            RETURN_TIME: 'وقت الاسترجاع',
            ARCHIVED_PICKUPS: 'أرشيف الاختار',
            ORDERS: 'طلبات',
            ENDED: 'منتهى'
        });
        $translateProvider.preferredLanguage('en');
        $translateProvider.useSanitizeValueStrategy(null);
        $translateProvider.useCookieStorage();
        tmhDynamicLocaleProvider.localeLocationPattern('commons/js/languages/angular-locale_{{locale}}.js');
    }

}());
